apiVersion: apps/v1
kind: Deployment 
metadata:
  name: App-Deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: cont1
          image: layareddy14/boardshack:latest
          ports:
            - containerPort: 8080 
